name: mlrose-ky
channels:
  - anaconda
  - defaults
dependencies:
  - python>=3.10, <3.13
  - pip
  - pip:
    - matplotlib~=3.8.4
    - networkx~=3.3
    - numpy~=1.26.4
    - pandas~=2.2.1
    - pytest~=8.3.2
    - scikit-learn~=1.5.0
    - scipy~=1.13.1
    - setuptools~=69.5.1
